In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
import torch
print(torch.__version__)

2.1.0+cu121


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


### Introduction to Tensors

### Creating tensors

#### pytorch tensors are created using tensor.torch

In [ ]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# Matrix
vec1 = torch.tensor([[7,7],[8,8]])

In [ ]:
vec1[0]

tensor([7, 7])

In [ ]:
print(vec1)
print(vec1.ndim)
vec1.shape

tensor([[7, 7],
        [8, 8]])
2


torch.Size([2, 2])

In [ ]:
# Tensor
tensor = torch.tensor([[[1,1],[1,2],[2,3]]])

In [ ]:
print(tensor)

tensor([[[1, 1],
         [1, 2],
         [2, 3]]])


In [ ]:
tensor.ndim

3

In [ ]:
tensor.shape

torch.Size([1, 3, 2])

In [ ]:
tensor[0]

tensor([[1, 1],
        [1, 2],
        [2, 3]])

In [ ]:
tensor[0][1]

tensor([1, 2])

### Random Tensors

In [ ]:
# create a random tensor
random_tensor = torch.rand(3,4) # torch.rand(size=(3,4)) --> this is also correct
random_tensor

tensor([[0.0372, 0.1529, 0.5518, 0.5106],
        [0.4527, 0.3134, 0.6058, 0.4790],
        [0.3755, 0.0856, 0.3054, 0.3500]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# create a random tensor similar to shape of image tensor
image_tensor = torch.rand(size=(224,224,3))  # height, width, color channels(R,G,B)

In [ ]:
image_tensor.shape, image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeroes and Ones

In [ ]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
torch.zeros(2,1)

tensor([[0.],
        [0.]])

In [ ]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

### Create a Range of tensors and tensors-like

In [ ]:
my_tensor = torch.arange(1,10,1)

In [ ]:
## If we want to create the tensor with similar shape of the tensor already existed
## we use tensors-like method

yours = torch.zeros_like(input=my_tensor)
yours

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [ ]:
### defualt dtype - float
## type() is used to convert one type to other
float_tensor = torch.tensor([3.0,6.0,9.0],
                            dtype=torch.float32,
                            device="cpu",   # it is the runtime/device (cpu,gpu)
                            requires_grad=False)  # if we want to track gradients for tensor

In [ ]:
float_tensor.dtype

torch.float32

In [ ]:
float_16 = float_tensor.type(torch.float16)
float_16

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
a = float_16 * float_tensor

In [ ]:
a.dtype

torch.float32

### Getting information from Tensors
Tensor Attributes






In [ ]:
### datatype - tensor.dtype
### shape -  tensor.shape
### size - tensor.size()
### device - tensor.device

In [ ]:
tens = torch.tensor([3,4])
tens.device

device(type='cpu')

### Tensor Operations



1.   Addition
2.   Subtraction
3.  Multiplication
4. Division
5. Matirx multiplication




In [ ]:
# Add
tensor = torch.tensor([1,2])
tensor + 10

tensor([11, 12])

In [ ]:
# Multiply
tensor * 20


tensor([20, 40])

In [ ]:
# Subtract
tensor - 1

tensor([0, 1])

In [ ]:
### Inbuilt functions

In [ ]:
torch.mul(tensor,10)

tensor([10, 20])

In [ ]:
torch.add(tensor,10)

tensor([11, 12])

In [ ]:
# Matirx multiplication


Two ways:
1. Element wise
2. General (what we know)

In [ ]:
# Element wise
print(tensor*tensor)

tensor([1, 4])


In [ ]:
t1= torch.tensor([[1,2],[1,2]])
print(t1*t1)

tensor([[1, 4],
        [1, 4]])


In [ ]:
# Matrix multiplication
torch.matmul(tensor,tensor)

tensor(5)

In [ ]:
%%time
torch.matmul(t1,t1)

CPU times: user 1.03 ms, sys: 4 µs, total: 1.03 ms
Wall time: 1.73 ms


tensor([[3, 6],
        [3, 6]])

In [ ]:
# matmul operation is same as symbol @ and shortcut torch.mm()

In [ ]:
t1 @ t1

tensor([[3, 6],
        [3, 6]])

In [ ]:
# Transpose
t1.T

tensor([[1, 1],
        [2, 2]])

Tensor Aggregation

In [ ]:
## Min,Max and Avg, Sum

In [ ]:
x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x.min(),torch.min(x)

(tensor(0), tensor(0))

In [ ]:
torch.max(x)

tensor(90)

In [ ]:
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
 ## torch.mean() requires a tensor of float32 dtype

In [ ]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [ ]:
torch.sum(x)

tensor(450)

In [ ]:
### Finding Positional Min and Max i.e., at which indices min and max are occuring

In [ ]:
x.argmin()

tensor(0)

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x.argmax()

tensor(9)

### Reshaping, Stacking, Squeezing and Unsqueezing tensors
  

*   Reshaping - reshapes an input tensor to a defined shape
*  Stacking - combines multiple tensors on top of one another (vstack) and side by side (hstack)
*  Squeeze - removes all '1' dimensions from a tensor
*  Unsqueeze - Add a '1' dimension to target tensor
*   Permute - Rearranges the dimensions of tensor
*   View -










In [ ]:
import torch

In [ ]:
x = torch.arange(1.,10.)

In [ ]:
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
# Add an extra dim
x_reshape = x.reshape(1,9)

In [ ]:
x_reshape, x_reshape.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
x.reshape(2,9)

RuntimeError: shape '[2, 9]' is invalid for input of size 9

In [ ]:
x.reshape(3,3)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [ ]:
## As we have seen, in reshape(), we can only give parameters which will give length
## of the tensor on multiplying

In [ ]:
# Stack tensors on top
x_stack = torch.stack([x,x,x,x],dim=0)
x_stack

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
torch.stack([x,x,x,x],dim=1)

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
torch.stack([x,x],dim=1)

tensor([[1., 1.],
        [2., 2.],
        [3., 3.],
        [4., 4.],
        [5., 5.],
        [6., 6.],
        [7., 7.],
        [8., 8.],
        [9., 9.]])

In [ ]:
# Squeeze - removes all single dimensions

In [ ]:
x_reshape, x_reshape.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
y= x_reshape.squeeze()

In [ ]:
y.shape

torch.Size([9])

In [ ]:
y

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
# Unsqueeze -  add a single dim to a target tensor at a specific dim

In [ ]:
y.shape  # when you are here again, try printing y and check

torch.Size([9])

In [ ]:
y.unsqueeze(0).shape

torch.Size([1, 9])

In [ ]:
## Indexing

In [ ]:
tens = torch.arange(1,10).reshape(1,3,3)
tens


tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
tens[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
tens[0][1]

tensor([4, 5, 6])

In [ ]:
tens[0][0][0]

tensor(1)

In [ ]:
tens[:,0] # all values of 0 dim

tensor([[1, 2, 3]])

In [ ]:
tens[:,1,0]

tensor([4])

### Pytorch tensors & Numpy

* Data in Numpy to pytorch tensor - torch.from_numpy(ndarray)
* Pytorch tensor to numpy - torch.Tensor.numpy()


In [ ]:
import torch
import numpy as np

In [ ]:
arr = np.arange(1.0,9.0)
tensor = torch.from_numpy(arr)

In [ ]:
arr,tensor

(array([1., 2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64))

In [ ]:
tensor = torch.ones(7)

In [ ]:
tensor

tensor([1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np_tensor = tensor.numpy()
tensor, np_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# random.seed()

In [ ]:
 # reproducible tensors

In [ ]:
random_seed = 42
torch.manual_seed(random_seed)
rand_tens_A = torch.rand(3,4)

# Everytime use randomseed
torch.manual_seed(random_seed)
rand_tens_B = torch.rand(3,4)

print(rand_tens_A)
print(rand_tens_B)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])


In [ ]:
print(rand_tens_A == rand_tens_B)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [ ]:
!nvidia-smi

Tue Jan 30 14:49:42 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   36C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
# check for gpu access
import torch
torch.cuda.is_available()

True

In [ ]:
# setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
torch.cuda.device_count()

1

### Use GPU

In [ ]:
# this tensor is on cpu by default
tens = torch.tensor([1,2])
print(tens)

tensor([1, 2])


In [ ]:
# Move tensor to GPU
tens_on_gpu = tens.to(device)
tens_on_gpu

tensor([1, 2], device='cuda:0')

In [ ]:
# Move tensor back to CPU
tensor_on_cpu = tens_on_gpu.cpu()
tensor_on_cpu

tensor([1, 2])